# Generated by Django 2.1.7 on 2019-02-27 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=300)),
                ('monthly', models.BooleanField(default=False)),
                ('weekly', models.BooleanField(default=False)),
                ('daily', models.BooleanField(default=False)),
                ('yearly', models.BooleanField(default=False)),
                ('priorty', models.IntegerField(default=0)),
                ('timeNow', models.DateTimeField(default=datetime.datetime(2019, 2, 27, 21, 11, 18, 554319))),
                ('timeScheduled', models.DateTimeField()),
            ],
        ),
    ]
