# Generated by Django 2.1.7 on 2019-04-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapi', '0005_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='severity',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=128),
        ),
    ]
